### ISSUE TITLE
build behind proxy not working

### ISSUE THREAD

**Issue by SaschaSchuenemann** [SUSE/sle2docker#11] opened 2015-06-01 18:56 UTC
I can't build the images behind our company proxy. With the earlier version 0.2.1 ( installed using zypper ) I failed at **Initializing image system on:**

Using version 0.2.4 I am able to go a couple of steps further. As the log shows, proxy settings are found and forwarded. But it seems, they get lost once the script uses chroot to step into the image.

sle2docker build -u *** -p *** SLE12

Starting build process inside of Docker container
Jun-01 18:44:12 <1> : Destination: /tmp/sle2docker20150601-25500-yazv16/result/build doesn't exist
Jun-01 18:44:13 <1> : Description provides no MD5 hash, check
Jun-01 18:44:13 <1> : Reading image description [Prepare]...
Jun-01 18:44:13 <1> : Setting up package manager: zypper             done
Jun-01 18:44:13 <1> : Setting up source channel:
Jun-01 18:44:13 <1> : --> https://nu.novell.com/SUSE/Products/SLE-SERVER/12/x86_64/product?credentials=NCCcredentials
Jun-01 18:44:13 <1> : Retain SLE12:Pool
Jun-01 18:44:13 <1> : Setting up source channel:
Jun-01 18:44:13 <1> : --> https://nu.novell.com/SUSE/Updates/SLE-SERVER/12/x86_64/update?credentials=NCCcredentials
Jun-01 18:44:13 <1> : Retain SLE12:Updates
Jun-01 18:44:13 <1> : Set root log: /tmp/sle2docker20150601-25500-yazv16/result/build/image-root.1.screenrc.log...                                   done
Jun-01 18:44:13 <1> : Creating credentials data                      done
Jun-01 18:44:13 <1> : Creating default template files for new root sydone
Jun-01 18:44:13 <1> : Importing build keys...Jun-01 18:44:13 <1> : Adding bootstrap zypper service: SLE12:Updates                                    done
Jun-01 18:44:13 <1> : Adding bootstrap zypper service: SLE12:Pool    done
Jun-01 18:46:22 <1> : Initializing image system on: /tmp/sle2docker20150601-25500-yazv16/result/build/image-root                                     done
Jun-01 18:46:49 <1> : Mounting required file systems                 done
Jun-01 18:46:49 <1> : Updating chroot zypper service: SLE12:Pool     done
Jun-01 18:46:49 <1> : Adding SLE12:Pool repo to image                done
Jun-01 18:46:50 <1> : Updating chroot zypper service: SLE12:Updates  done
Jun-01 18:46:50 <1> : Adding SLE12:Updates repo to image             done
Jun-01 18:46:50 <1> : Installing image packages...+ export PBL_SKIP_BOOT_TEST=1
+ PBL_SKIP_BOOT_TEST=1
+ export http_proxy=http://***:**/
+ http_proxy=http://***:**/
+ trap clean INT TERM
+ export ZYPP_MODALIAS_SYSFS=/tmp
+ ZYPP_MODALIAS_SYSFS=/tmp
+ export YAST_IS_RUNNING=true
+ YAST_IS_RUNNING=true
+ export ZYPP_CONF=/var/cache/kiwi/zypper/zypp.conf.1
+ ZYPP_CONF=/var/cache/kiwi/zypper/zypp.conf.1
+ chroot /tmp/sle2docker20150601-25500-yazv16/result/build/image-root mkdir -p /etc/zypp
+ SPID=831
+ wait 831
+ chroot /tmp/sle2docker20150601-25500-yazv16/result/build/image-root zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /var/cache/kiwi/zypper/repos --solv-cache-dir /var/cache/kiwi/zypper/solv --cache-dir /var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.1 --no-gpg-checks install --auto-agree-with-licenses --no-recommends coreutils iputils
Download (curl) error for 'https://nu.novell.com/SUSE/Products/SLE-SERVER/12/x86_64/product/x86_64/iputils-s20121221-2.19.x86_64.rpm?credentials=NCCcredentials':
Error code: Connection failed
Error message: Failed to connect to nu.novell.com port 443: No route to host

Problem occured during or after installation or removal of packages:
Installation aborted by user

Please see the above error message for a hint.
+ ECODE=4
+ echo 4
+ exit 4
                                                                     failed
Jun-01 18:46:53 <3> : Image installation failed                      failed
Jun-01 18:46:53 <3> : KIWI exited with error(s)
Jun-01 18:46:53 <1> : Complete logfile at: /tmp/sle2docker20150601-25500-yazv16/result/build/image-root.log
Something wrong happened during the build process

**Comment by SaschaSchuenemann** [comment] 2015-06-01 19:36
Retrieving the file directly using curl works fine. And as mentioned earlier, when disabling the proxy, the script fails a couple of steps earlier.

So some parts of it use the proxy. I'm wondering what is different with the part of the script..

here is an extract from the longer log file

Jun-01 19:30:53 <1> : UmJun-01 19:30:51 <1> : Installing image packages...Jun-01 19:30:51 <1> : EXEC [chmod 755 /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/screenrc.smart]
+ export PBL_SKIP_BOOT_TEST=1
+ PBL_SKIP_BOOT_TEST=1
+ export http_proxy=http://***:**/
+ http_proxy=http://***:**/
+ trap clean INT TERM
+ export ZYPP_MODALIAS_SYSFS=/tmp
+ ZYPP_MODALIAS_SYSFS=/tmp
+ export YAST_IS_RUNNING=true
+ YAST_IS_RUNNING=true
+ export ZYPP_CONF=/var/cache/kiwi/zypper/zypp.conf.1
+ ZYPP_CONF=/var/cache/kiwi/zypper/zypp.conf.1
+ chroot /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root mkdir -p /etc/zypp
+ SPID=819
+ wait 819
+ chroot /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /var/cache/kiwi/zypper/repos --solv-cache-dir /var/cache/kiwi/zypper/solv --cache-dir /var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.1 --no-gpg-checks install --auto-agree-with-licenses --no-recommends coreutils iputils
Warning: The /etc/products.d/baseproduct symlink is dangling or missing!
The link must point to your core products .prod file in /etc/products.d.

Building repository 'SLE12:Pool' cache ...................................[done]
Building repository 'SLE12:Updates' cache ................................[done]
Loading repository data...
Reading installed packages...
'coreutils' is already installed.
No update candidate for 'coreutils-8.22-5.17.x86_64'. The highest available version is already installed.
Resolving package dependencies...

The following NEW package is going to be installed:
  iputils 

1 new package to install.
Overall download size: 90.7 KiB. Already cached: 0 B  After the operation, 
additional 244.4 KiB will be used.
Continue? [y/n/? shows all options] (y): y
Retrieving package iputils-s20121221-2.19.x86_64
                                           (1/1),  90.7 KiB (244.4 KiB unpacked)
Retrieving: iputils-s20121221-2.19.x86_64.rpm ...........................[error]
Download (curl) error for 'https://nu.novell.com/SUSE/Products/SLE-SERVER/12/x86_64/product/x86_64/iputils-s20121221-2.19.x86_64.rpm?credentials=NCCcredentials':
Error code: Connection failed
Error message: Failed to connect to nu.novell.com port 443: No route to host

Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Problem occured during or after installation or removal of packages:
Installation aborted by user

Please see the above error message for a hint.
+ ECODE=4
+ echo 4
+ exit 4
Jun-01 19:30:53 <1> : EXEC [rm -f /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/screenrc.smart*]
Jun-01 19:30:53 <1> : EXEC [rm -f /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/screenrc.ctrls]
Jun-01 19:30:53 <1> : EXEC [rm -f /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/screenrc.err]

Jun-01 19:30:53 <1> : Release package manager lock
Jun-01 19:30:53 <1> : EXEC [rm -f /var/lock/kiwi-init.lock]
Jun-01 19:30:53 <3> : Image installation failed
Jun-01 19:30:53 <3> : KIWI exited with error(s)
Jun-01 19:30:53 <1> : EXEC [mv /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root.1.screenrc.log /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root.log 2>&1]
Jun-01 19:30:53 <1> : Complete logfile at: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root.log
Jun-01 19:30:53 <1> : Release package manager lock
Jun-01 19:30:53 <1> : EXEC [rm -f /var/lock/kiwi-init.lock]
Jun-01 19:30:53 <1> : Release package manager lock
Jun-01 19:30:53 <1> : EXEC [rm -f /var/lock/kiwi-init.lock]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root//var/cache/kiwi"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root//var/cache/kiwi
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root//var/cache/kiwi" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc/sys/fs/binfmt_misc"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc/sys/fs/binfmt_misc
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc/sys/fs/binfmt_misc" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev/pts"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev/pts
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev/pts" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/sys"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/sys
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/sys" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/var/run/dbus"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/var/run/dbus
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/var/run/dbus" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc" 2>&1]
Jun-01 19:30:53 <1> : EXEC [rm -f /var/cache/kiwi/zypper/zypper.conf.1 /var/cache/kiwi/zypper/zypp.conf.1]
ounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/var/run/dbus
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/var/run/dbus" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/dev" 2>&1]
Jun-01 19:30:53 <1> : EXEC [test -d "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc"]
Jun-01 19:30:53 <1> : Umounting path: /tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc
Jun-01 19:30:53 <1> : EXEC [umount "/tmp/sle2docker20150601-2291-1govy3w/result/build/image-root/proc" 2>&1]
Jun-01 19:30:53 <1> : EXEC [rm -f /var/cache/kiwi/zypper/zypper.conf.1 /var/cache/kiwi/zypper/zypp.conf.1]

**Comment by holgerreif** [comment] 2015-06-02 16:58
Contrary to what was stated in issue#1 the problem was not solved by adding support for http_proxy.
I had to edit the follwing files
/usr/lib64/ruby/gems/2.1.0/gems/sle2docker-0.2.3/lib/sle2docker/builder.rb
/usr/lib64/ruby/gems/2.1.0/gems/sle2docker-0.2.3/lib/sle2docker/cli.rb

and to duplicate the few lines that deal with http_proxy and change to https_proxy in the duplicate.

I hope this gets added soon.

**Comment by flavio** [comment] 2015-06-02 17:50
This can be updated even sooner if you share the patch you wrote :)

**Comment by holgerreif** [comment] 2015-06-03 08:18
Sure, here it comes:

 # diff -ur sle2docker-0.2.3/lib/sle2docker{.org,}
diff -ur sle2docker-0.2.3/lib/sle2docker.org/builder.rb sle2docker-0.2.3/lib/sle2docker/builder.rb
--- sle2docker-0.2.3/lib/sle2docker.org/builder.rb      2014-11-27 21:36:55.000000000 +0100
+++ sle2docker-0.2.3/lib/sle2docker/builder.rb  2015-06-03 09:00:41.574086656 +0200
@@ -34,6 +34,10 @@
       if @options[:http_proxy]
         docker_cmd += "-e http_proxy=#{@options[:http_proxy]} "
       end
+      # the HTTPS proxy specified by the user
+      if @options[:https_proxy]
+        docker_cmd += "-e https_proxy=#{@options[:https_proxy]} "
+      end
       # ensure kiwi cache is persistent
       docker_cmd += "-v /var/cache/kiwi:/var/cache/kiwi "
       # share build dir
diff -ur sle2docker-0.2.3/lib/sle2docker.org/cli.rb sle2docker-0.2.3/lib/sle2docker/cli.rb
--- sle2docker-0.2.3/lib/sle2docker.org/cli.rb  2014-11-27 21:36:55.000000000 +0100
+++ sle2docker-0.2.3/lib/sle2docker/cli.rb      2015-06-02 18:27:09.836659491 +0200
@@ -76,6 +76,9 @@
     method_option :http_proxy, :aliases => ["--http-proxy"],
                   :default => ENV['http_proxy'],
                   :desc => "HTTP proxy to use (eg: http://squid.local:3128)"
+    method_option :https_proxy, :aliases => ["--https-proxy"],
+                  :default => ENV['https_proxy'],
+                  :desc => "HTTPS proxy to use (eg: http://squid.local:3128)"
     def build(template_name)
       template_dir = Template.template_dir(template_name)
       builder = Builder.new(options)

Some comments regarding proxy stuff.

The problems I (and others) observed seem to be hard to reproduce. 
My yesterday's test did not work with --http_proxy, but with the modified version and --https_proxy option. Re-test with --http_proxy again failed as before.
My today's test (after host reboot) showed, that --http_proxy alone did work (contrary to yesterday).

Further tests showed, that proxy environment settings were propagated to the running opensuse/kiwi container, e.g. 
http_proxy=http://<proxyip>:<proxyport> sle2docker build SLE11SP3
was equivalent to
sle2docker build SLE11SP3 --http_proxy=http://<proxyip>:<proxyport>

Furthermore several tests results suggest, that zypper uses http_proxy value for https connections too if https_proxy is not set.

Thus I conclude there are workarounds, however explicitely specifying https_proxy would be great!

**Comment by flavio** [comment] 2015-06-17 08:38
Closing, starting from version 0.4.0 it will no longer be possible to build the SLE Docker images from the templates. Only pre-built images are going to be available.

**Closed by flavio** 2015-06-17 08:38 UTC
